"use client";

import { useEffect, useState } from "react";
import axios from "axios";
import ReactMarkdown from "react-markdown";
import { useParams, useRouter } from "next/navigation";
import { ArrowLeft, BookOpen, CheckCircle, Loader2 } from "lucide-react";
import Link from "next/link";
import { cn } from "@/lib/utils";

interface StudyPlan {
    exam_id: string;
    markdown_plan: string;
    raw_json: any;
}

export default function PlanView() {
    const { id } = useParams();
    const router = useRouter();
    const [plan, setPlan] = useState<StudyPlan | null>(null);
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState<string | null>(null);

    useEffect(() => {
        if (!id) return;

        const fetchPlan = async () => {
            try {
                const res = await axios.get(`http://localhost:8000/plans/${id}`);
                setPlan(res.data);
            } catch (err) {
                console.error(err);
                setError("Could not load study plan.");
            } finally {
                setLoading(false);
            }
        };

        fetchPlan();
    }, [id]);

    if (loading) {
        return (
            <div className="min-h-screen flex flex-col items-center justify-center bg-slate-50">
                <Loader2 className="w-12 h-12 text-blue-600 animate-spin mb-4" />
                <p className="text-slate-500 font-medium">Generating your plan...</p>
            </div>
        );
    }

    if (error || !plan) {
        return (
            <div className="min-h-screen flex flex-col items-center justify-center bg-slate-50 text-center p-6">
                <div className="w-16 h-16 bg-red-100 text-red-600 rounded-full flex items-center justify-center mb-4 mx-auto">
                    <BookOpen className="w-8 h-8" />
                </div>
                <h2 className="text-xl font-bold text-slate-900 mb-2">Plan Not Found</h2>
                <p className="text-slate-500 mb-6">{error || "This plan doesn't exist yet."}</p>
                <Link
                    href="/"
                    className="bg-slate-900 text-white px-6 py-2 rounded-lg font-medium hover:bg-slate-800 transition-colors"
                >
                    Go Back Home
                </Link>
            </div>
        );
    }

    return (
        <div className="min-h-screen bg-white">
            {/* Navigation */}
            <nav className="sticky top-0 z-10 bg-white/80 backdrop-blur-md border-b border-slate-200 px-6 py-4 flex items-center justify-between">
                <Link
                    href="/"
                    className="flex items-center text-slate-500 hover:text-slate-900 transition-colors font-medium"
                >
                    <ArrowLeft className="w-5 h-5 mr-2" />
                    Back to Dashboard
                </Link>
                <div className="font-bold text-slate-900">Study Plan</div>
                <div className="w-20"></div> {/* Spacer for centering */}
            </nav>

            {/* Content */}
            <main className="max-w-3xl mx-auto px-6 py-10">
                <article className="prose prose-slate lg:prose-lg max-w-none">
                    <ReactMarkdown>
                        {plan.markdown_plan}
                    </ReactMarkdown>
                </article>

                {/* Footer Actions */}
                <div className="mt-16 pt-8 border-t border-slate-100 flex flex-col sm:flex-row items-center justify-between gap-4">
                    <p className="text-slate-400 text-sm">
                        Generated by DadTutor AI
                    </p>
                    <button
                        onClick={() => window.print()}
                        className="text-blue-600 font-medium hover:underline"
                    >
                        Print / Save as PDF
                    </button>
                </div>
            </main>
        </div>
    );
}
